import csv

# Define the architecture for each network
architectures = {
    "VGG16": [
        ["Input Height", "224"],
        ["Input Width", "224"],
        ["Input Channels", "3"],
        ["convolution", "3", "3", "64", "1", "1", "relu"],
        ["convolution", "3", "3", "64", "1", "1", "relu"],
        ["maxpooling", "2", "2", "2", "0"],
        ["convolution", "3", "3", "128", "1", "1", "relu"],
        ["convolution", "3", "3", "128", "1", "1", "relu"],
        ["maxpooling", "2", "2", "2", "0"],
        ["convolution", "3", "3", "256", "1", "1", "relu"],
        ["convolution", "3", "3", "256", "1", "1", "relu"],
        ["convolution", "3", "3", "256", "1", "1", "relu"],
        ["maxpooling", "2", "2", "2", "0"],
        ["convolution", "3", "3", "512", "1", "1", "relu"],
        ["convolution", "3", "3", "512", "1", "1", "relu"],
        ["convolution", "3", "3", "512", "1", "1", "relu"],
        ["maxpooling", "2", "2", "2", "0"],
        ["convolution", "3", "3", "512", "1", "1", "relu"],
        ["convolution", "3", "3", "512", "1", "1", "relu"],
        ["convolution", "3", "3", "512", "1", "1", "relu"],
        ["maxpooling", "2", "2", "2", "0"],
        ["flatten"],
        ["dense", "4096", "relu"],
        ["dense", "4096", "relu"],
        ["dense", "1000", "softmax"]
    ],
    "VGG19": [
        ["Input Height", "224"],
        ["Input Width", "224"],
        ["Input Channels", "3"],
        ["convolution", "3", "3", "64", "1", "1", "relu"],
        ["convolution", "3", "3", "64", "1", "1", "relu"],
        ["maxpooling", "2", "2", "2", "0"],
        ["convolution", "3", "3", "128", "1", "1", "relu"],
        ["convolution", "3", "3", "128", "1", "1", "relu"],
        ["maxpooling", "2", "2", "2", "0"],
        ["convolution", "3", "3", "256", "1", "1", "relu"],
        ["convolution", "3", "3", "256", "1", "1", "relu"],
        ["convolution", "3", "3", "256", "1", "1", "relu"],
        ["convolution", "3", "3", "256", "1", "1", "relu"],
        ["maxpooling", "2", "2", "2", "0"],
        ["convolution", "3", "3", "512", "1", "1", "relu"],
        ["convolution", "3", "3", "512", "1", "1", "relu"],
        ["convolution", "3", "3", "512", "1", "1", "relu"],
        ["convolution", "3", "3", "512", "1", "1", "relu"],
        ["maxpooling", "2", "2", "2", "0"],
        ["convolution", "3", "3", "512", "1", "1", "relu"],
        ["convolution", "3", "3", "512", "1", "1", "relu"],
        ["convolution", "3", "3", "512", "1", "1", "relu"],
        ["convolution", "3", "3", "512", "1", "1", "relu"],
        ["maxpooling", "2", "2", "2", "0"],
        ["flatten"],
        ["dense", "4096", "relu"],
        ["dense", "4096", "relu"],
        ["dense", "1000", "softmax"]
    ],
    "ResNet50": [
        ["Input Height", "224"],
        ["Input Width", "224"],
        ["Input Channels", "3"],
        ["convolution", "7", "7", "64", "2", "3", "relu"],
        ["maxpooling", "3", "3", "2", "0"],
        ["convolution", "1", "1", "64", "1", "0", "relu"],
        ["convolution", "3", "3", "64", "1", "1", "relu"],
        ["convolution", "1", "1", "256", "1", "0", "relu"],
        ["convolution", "1", "1", "128", "2", "0", "relu"],
        ["convolution", "3", "3", "128", "1", "1", "relu"],
        ["convolution", "1", "1", "512", "1", "0", "relu"],
        ["convolution", "1", "1", "256", "2", "0", "relu"],
        ["convolution", "3", "3", "256", "1", "1", "relu"],
        ["convolution", "1", "1", "1024", "1", "0", "relu"],
        ["convolution", "1", "1", "512", "2", "0", "relu"],
        ["convolution", "3", "3", "512", "1", "1", "relu"],
        ["convolution", "1", "1", "2048", "1", "0", "relu"],
        ["averagepooling", "7", "7", "1", "0"],
        ["flatten"],
        ["dense", "1000", "softmax"]
    ],
    "ResNet101": [
        ["Input Height", "224"],
        ["Input Width", "224"],
        ["Input Channels", "3"],
        ["convolution", "7", "7", "64", "2", "3", "relu"],
        ["maxpooling", "3", "3", "2", "0"],
        ["convolution", "1", "1", "64", "1", "0", "relu"],
        ["convolution", "3", "3", "64", "1", "1", "relu"],
        ["convolution", "1", "1", "256", "1", "0", "relu"],
        ["convolution", "1", "1", "128", "2", "0", "relu"],
        ["convolution", "3", "3", "128", "1", "1", "relu"],
        ["convolution", "1", "1", "512", "1", "0", "relu"],
        ["convolution", "1", "1", "256", "2", "0", "relu"],
        ["convolution", "3", "3", "256", "1", "1", "relu"],
        ["convolution", "1", "1", "1024", "1", "0", "relu"],
        ["convolution", "1", "1", "512", "2", "0", "relu"],
        ["convolution", "3", "3", "512", "1", "1", "relu"],
        ["convolution", "1", "1", "2048", "1", "0", "relu"],
        ["averagepooling", "7", "7", "1", "0"],
        ["flatten"],
        ["dense", "1000", "softmax"]
    ],
    "ResNet152": [
        ["Input Height", "224"],
        ["Input Width", "224"],
        ["Input Channels", "3"],
        ["convolution", "7", "7", "64", "2", "3", "relu"],
        ["maxpooling", "3", "3", "2", "0"],
        ["convolution", "1", "1", "64", "1", "0", "relu"],
        ["convolution", "3", "3", "64", "1", "1", "relu"],
        ["convolution", "1", "1", "256", "1", "0", "relu"],
        ["convolution", "1", "1", "128", "2", "0", "relu"],
        ["convolution", "3", "3", "128", "1", "1", "relu"],
        ["convolution", "1", "1", "512", "1", "0", "relu"],
        ["convolution", "1", "1", "256", "2", "0", "relu"],
        ["convolution", "3", "3", "256", "1", "1", "relu"],
        ["convolution", "1", "1", "1024", "1", "0", "relu"],
        ["convolution", "1", "1", "512", "2", "0", "relu"],
        ["convolution", "3", "3", "512", "1", "1", "relu"],
        ["convolution", "1", "1", "2048", "1", "0", "relu"],
        ["averagepooling", "7", "7", "1", "0"],
        ["flatten"],
        ["dense", "1000", "softmax"]
    ],
    "InceptionV3": [
        ["Input Height", "299"],
        ["Input Width", "299"],
        ["Input Channels", "3"],
        ["convolution", "3", "3", "32", "2", "0", "relu"],
        ["convolution", "3", "3", "32", "1", "0", "relu"],
        ["convolution", "3", "3", "64", "1", "1", "relu"],
        ["maxpooling", "3", "3", "2", "0"],
        ["convolution", "1", "1", "80", "1", "0", "relu"],
        ["convolution", "3", "3", "192", "1", "0", "relu"],
        ["maxpooling", "3", "3", "2", "0"],
        ["mixed0"],
        ["mixed1"],
        ["mixed2"],
        ["mixed3"],
        ["mixed4"],
        ["mixed5"],
        ["mixed6"],
        ["mixed7"],
        ["mixed8"],
        ["mixed9"],
        ["mixed10"],
        ["averagepooling", "8", "8", "1", "0"],
        ["flatten"],
        ["dense", "1000", "softmax"]
    ]
    }

# Create the CSV file
with open('neural_networks.csv', mode='w', newline='') as file:
    writer = csv.writer(file)
    
    for net_name, layers in architectures.items():
        writer.writerow(["Configuration", net_name])
        for layer in layers:
            writer.writerow(layer)
        writer.writerow([]) 